/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ControlRouteImport } from './routes/control'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LiveRouteImport } from './routes/live'
import { Route as RouteIndexRouteImport } from './routes/route/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteIndexRoute = RouteIndexRouteImport.update({
  id: '/route/',
  path: '/route/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/ask': typeof AskRoute
  '/audit': typeof AuditRoute
  '/control': typeof ControlRoute
  '/inbox': typeof InboxRoute
  '/live': typeof LiveRoute
  '/route/': typeof RouteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/ask': typeof AskRoute
  '/audit': typeof AuditRoute
  '/control': typeof ControlRoute
  '/inbox': typeof InboxRoute
  '/live': typeof LiveRoute
  '/route': typeof RouteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/ask': typeof AskRoute
  '/audit': typeof AuditRoute
  '/control': typeof ControlRoute
  '/inbox': typeof InboxRoute
  '/live': typeof LiveRoute
  '/route/': typeof RouteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/ask'
    | '/audit'
    | '/control'
    | '/inbox'
    | '/live'
    | '/route/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/ask'
    | '/audit'
    | '/control'
    | '/inbox'
    | '/live'
    | '/route'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/ask'
    | '/audit'
    | '/control'
    | '/inbox'
    | '/live'
    | '/route/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AskRoute: typeof AskRoute
  AuditRoute: typeof AuditRoute
  ControlRoute: typeof ControlRoute
  InboxRoute: typeof InboxRoute
  LiveRoute: typeof LiveRoute
  RouteIndexRoute: typeof RouteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route/': {
      id: '/route/'
      path: '/route'
      fullPath: '/route/'
      preLoaderRoute: typeof RouteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  AskRoute: AskRoute,
  AuditRoute: AuditRoute,
  ControlRoute: ControlRoute,
  InboxRoute: InboxRoute,
  LiveRoute: LiveRoute,
  RouteIndexRoute: RouteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
