/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LiveRouteImport } from './routes/live'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppApprovalsRouteImport } from './routes/app/approvals'
import { Route as AppAskRouteImport } from './routes/app/ask'
import { Route as AppAuditRouteImport } from './routes/app/audit'
import { Route as AppControlRouteImport } from './routes/app/control'
import { Route as AppInboxRouteImport } from './routes/app/inbox'
import { Route as AppRouteIndexRouteImport } from './routes/app/route/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAskRoute = AppAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppControlRoute = AppControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppRouteIndexRoute = AppRouteIndexRouteImport.update({
  id: '/route/',
  path: '/route/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/live': typeof LiveRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/ask': typeof AppAskRoute
  '/app/audit': typeof AppAuditRoute
  '/app/control': typeof AppControlRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/': typeof AppIndexRoute
  '/app/route/': typeof AppRouteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/ask': typeof AppAskRoute
  '/app/audit': typeof AppAuditRoute
  '/app/control': typeof AppControlRoute
  '/app/inbox': typeof AppInboxRoute
  '/app': typeof AppIndexRoute
  '/app/route': typeof AppRouteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/live': typeof LiveRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/ask': typeof AppAskRoute
  '/app/audit': typeof AppAuditRoute
  '/app/control': typeof AppControlRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/': typeof AppIndexRoute
  '/app/route/': typeof AppRouteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/live'
    | '/app/approvals'
    | '/app/ask'
    | '/app/audit'
    | '/app/control'
    | '/app/inbox'
    | '/app/'
    | '/app/route/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/live'
    | '/app/approvals'
    | '/app/ask'
    | '/app/audit'
    | '/app/control'
    | '/app/inbox'
    | '/app'
    | '/app/route'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/live'
    | '/app/approvals'
    | '/app/ask'
    | '/app/audit'
    | '/app/control'
    | '/app/inbox'
    | '/app/'
    | '/app/route/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LiveRoute: typeof LiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ask': {
      id: '/app/ask'
      path: '/ask'
      fullPath: '/app/ask'
      preLoaderRoute: typeof AppAskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/control': {
      id: '/app/control'
      path: '/control'
      fullPath: '/app/control'
      preLoaderRoute: typeof AppControlRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/route/': {
      id: '/app/route/'
      path: '/route'
      fullPath: '/app/route/'
      preLoaderRoute: typeof AppRouteIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAskRoute: typeof AppAskRoute
  AppAuditRoute: typeof AppAuditRoute
  AppControlRoute: typeof AppControlRoute
  AppInboxRoute: typeof AppInboxRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRouteIndexRoute: typeof AppRouteIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalsRoute: AppApprovalsRoute,
  AppAskRoute: AppAskRoute,
  AppAuditRoute: AppAuditRoute,
  AppControlRoute: AppControlRoute,
  AppInboxRoute: AppInboxRoute,
  AppIndexRoute: AppIndexRoute,
  AppRouteIndexRoute: AppRouteIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LiveRoute: LiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
